version: "3.9"
services:
  redis:
    image: "redis:latest"
    container_name: redis
    hostname: redis
    command: ["redis-server", "--requirepass", "AetHXRbYvs8G5xWP"]
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master